---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap
    # The roles buildtools, python_pip and postgres are required.
    # bareos-dir needs to connect to a database.
    - role: buluma.buildtools
    # EPEL is required for RHEL7.
    - role: buluma.epel
    - role: buluma.python_pip
    - role: buluma.postgres
    # The roles core_dependencies and postfix are  required for the `bareos_role`: "dir".
    # bareos-dir needs to send emails.
    # - role: buluma.core_dependencies
    # - role: buluma.postfix
    - role: buluma.bareos_repository
      bareos_repository_enable_tracebacks: yes
